=== mkoshko/epam-adventure/task04/data/banks.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.training.by/banks"
        xmlns="http://www.epam.training.by/banks"
        elementFormDefault="qualified">
    <xs:element name="banks">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="bank" type="bank"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="bank">
        <xs:sequence>
            <xs:element name="name" type="xs:normalizedString"/>
            <xs:element name="deposit" type="deposit" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="country" type="xs:string" use="required"/>
        <xs:attribute name="site" type="xs:string" use="optional"/>
        <xs:attribute name="licence" type="xs:boolean" default="true"/>
    </xs:complexType>

    <xs:complexType name="deposit">
        <xs:sequence>
            <xs:element name="type" type="type"/>
            <xs:element name="iban" type="iban"/>
            <xs:element name="depositor" type="depositor"/>
            <xs:element name="depositDate" type="xs:date"/>
            <xs:element name="amount" type="positiveDouble"/>
            <xs:element name="currency" type="currency"/>
            <xs:element name="profitability" type="profitability"/>
            <xs:element name="term" type="term"/>
            <xs:element name="withdrawal" type="xs:boolean"/>
            <xs:element name="refill" type="xs:boolean"/>
            <xs:element name="capitalization" type="xs:boolean"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:ID" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="savingDeposit">
        <xs:complexContent>
            <xs:extension base="deposit">
                <xs:sequence>
                    <xs:element name="payout" type="payout"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="settlementDeposit">
        <xs:complexContent>
            <xs:extension base="deposit">
                <xs:sequence>
                    <xs:element name="minBalance" type="positiveDouble"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="До востребования"/>
            <xs:enumeration value="Срочный"/>
            <xs:enumeration value="Сберегательный"/>
            <xs:enumeration value="Накопительный"/>
            <xs:enumeration value="Расчетный"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="iban">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2}[0-9]{2}[A-Z]{4}[0-9]{4}[0-9]{16}"/> <!--BY51MMBN84682548654823479652-->
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="depositor">
        <xs:sequence>
            <xs:element name="firstName" type="xs:normalizedString"/>
            <xs:element name="middleName" type="xs:normalizedString"/>
            <xs:element name="lastName" type="xs:normalizedString"/>
            <xs:element name="identification">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{7}[A-Z][0-9]{3}[A-Z]{2}[0-9]"/> <!--4536585F354DS2-->
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="positiveDouble">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="currency">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BYR"/>
            <xs:enumeration value="USD"/>
            <xs:enumeration value="RUB"/>
            <xs:enumeration value="EUR"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="profitability">
        <xs:restriction base="positiveDouble">
            <xs:maxInclusive value="100.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="term">
        <xs:union memberTypes="xs:positiveInteger undetermined"/>
    </xs:simpleType>

    <xs:simpleType name="undetermined">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Не установлен"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="payout">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ежемесячно"/>
            <xs:enumeration value="Поквартально"/>
            <xs:enumeration value="В конце срока"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== mkoshko/epam-adventure/task04/data/banks.xml
<?xml version="1.0" encoding="UTF-8" ?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.epam.training.by/banks"
       xsi:schemaLocation="http://www.epam.training.by/banks banks.xsd">
    <bank country="Беларусь" site="www.belarusbank.by" licence="true">
        <name>БеларусБанк</name>
        <deposit ID="DD0001">
            <type>До востребования</type>
            <iban>BY51MMBN84682548654823479652</iban>
            <depositor>
                <firstName>Максим</firstName>
                <middleName>Игоревич</middleName>
                <lastName>Кошко</lastName>
                <identification>4536585F354DS2</identification>
            </depositor>
            <depositDate>2019-08-26</depositDate>
            <amount>1000</amount>
            <currency>USD</currency>
            <profitability>9</profitability>
            <term>Не установлен</term>
            <withdrawal>true</withdrawal>
            <refill>false</refill>
            <capitalization>true</capitalization>
        </deposit>
    </bank>
    <bank country="Беларусь" site="www.ideabank.by" licence="true">
        <name>Идея Банк</name>
        <deposit ID="DD0002">
            <type>Накопительный</type>
            <iban>BY34IDBN15478648654823479652</iban>
            <depositor>
                <firstName>Асер</firstName>
                <middleName>Предаторович</middleName>
                <lastName>Лептопов</lastName>
                <identification>7634985F354DS2</identification>
            </depositor>
            <depositDate>2018-12-07</depositDate>
            <amount>2500</amount>
            <currency>BYR</currency>
            <profitability>6</profitability>
            <term>12</term>
            <withdrawal>true</withdrawal>
            <refill>true</refill>
            <capitalization>false</capitalization>
        </deposit>
    </bank>
    <bank country="Беларусь" site="www.belveb.by" licence="true">
        <name>Банк БелВЭБ</name>
        <deposit ID="DD0003" xsi:type="settlementDeposit">
            <type>Расчетный</type>
            <iban>BY34BVBN15478648654824763452</iban>
            <depositor>
                <firstName>Elon</firstName>
                <middleName>Reeve</middleName>
                <lastName>Musk</lastName>
                <identification>0000000A000AA0</identification>
            </depositor>
            <depositDate>2002-05-06</depositDate>
            <amount>33390238900</amount>
            <currency>USD</currency>
            <profitability>20.4</profitability>
            <term>6</term>
            <withdrawal>true</withdrawal>
            <refill>true</refill>
            <capitalization>false</capitalization>
            <minBalance>250000</minBalance>
        </deposit>
    </bank>
    <bank country="Беларусь" site="www.mmbank.by" licence="false">
        <name>Банк Дабрабыт</name>
        <deposit ID="DD0004" xsi:type="savingDeposit">
            <type>Сберегательный</type>
            <iban>BY34MMBN15477638654824761357</iban>
            <depositor>
                <firstName>William</firstName>
                <middleName>Henry</middleName>
                <lastName>Gates</lastName>
                <identification>7634575C354SD2</identification>
            </depositor>
            <depositDate>1975-04-04</depositDate>
            <amount>135000</amount>
            <currency>USD</currency>
            <profitability>100.0</profitability>
            <term>12</term>
            <withdrawal>false</withdrawal>
            <refill>false</refill>
            <capitalization>false</capitalization>
            <payout>Ежемесячно</payout>
        </deposit>
    </bank>
    <bank country="Беларусь" site="alfa-bank.by" licence="true">
        <name>Альфа-Банк</name>
        <deposit ID="DD0005">
            <type>Срочный</type>
            <iban>BY34MMBN15477638654824761357</iban>
            <depositor>
                <firstName>Лоуренс</firstName>
                <middleName>Эдвард</middleName>
                <lastName>Пейдж</lastName>
                <identification>3434885G354SD3</identification>
            </depositor>
            <depositDate>1998-09-04</depositDate>
            <amount>4500</amount>
            <currency>USD</currency>
            <profitability>48.6</profitability>
            <term>300</term>
            <withdrawal>false</withdrawal>
            <refill>true</refill>
            <capitalization>true</capitalization>
        </deposit>
    </bank>
    <bank country="Беларусь" site="www.bps-sberbank.by" licence="true">
        <name>БПС-Сбербанк</name>
        <deposit ID="DD0006" xsi:type="settlementDeposit">
            <type>Расчетный</type>
            <iban>BY34BVBN15478548962458243452</iban>
            <depositor>
                <firstName>Александр</firstName>
                <middleName>Сергеевич</middleName>
                <lastName>Пушкин</lastName>
                <identification>0000000A000AA0</identification>
            </depositor>
            <depositDate>2019-01-06</depositDate>
            <amount>500</amount>
            <currency>RUB</currency>
            <profitability>5</profitability>
            <term>12</term>
            <withdrawal>true</withdrawal>
            <refill>true</refill>
            <capitalization>false</capitalization>
            <minBalance>150</minBalance>
        </deposit>
    </bank>
    <bank country="Беларусь" site="www.vtb-bank.by" licence="true">
        <name>ВТБ Беларусь</name>
        <deposit ID="DD0007">
            <type>До востребования</type>
            <iban>BY51MMBN84682578696596848246</iban>
            <depositor>
                <firstName>Плутон</firstName>
                <middleName>Солнцевич</middleName>
                <lastName>Млечнепутов</lastName>
                <identification>4568428F354DS2</identification>
            </depositor>
            <depositDate>2018-04-26</depositDate>
            <amount>6500</amount>
            <currency>BYR</currency>
            <profitability>12</profitability>
            <term>Не установлен</term>
            <withdrawal>true</withdrawal>
            <refill>false</refill>
            <capitalization>true</capitalization>
        </deposit>
    </bank>
    <bank country="Беларусь" site="www.belgazprombank.by" licence="true">
        <name>БелГазпромБанк</name>
        <deposit ID="DD0008" xsi:type="settlementDeposit">
            <type>Расчетный</type>
            <iban>BY34BVBN15476546434863453452</iban>
            <depositor>
                <firstName>Кило</firstName>
                <middleName>Ом</middleName>
                <lastName>Сопротивляев</lastName>
                <identification>6578500A000AA0</identification>
            </depositor>
            <depositDate>2019-07-06</depositDate>
            <amount>5000</amount>
            <currency>EUR</currency>
            <profitability>4.5</profitability>
            <term>12</term>
            <withdrawal>true</withdrawal>
            <refill>true</refill>
            <capitalization>false</capitalization>
            <minBalance>250000</minBalance>
        </deposit>
    </bank>
    <bank country="Беларусь" site="	www.belapb.by" licence="true">
        <name>БелАгроПромБанк</name>
        <deposit ID="DD0009">
            <type>Накопительный</type>
            <iban>BY34IDBN15478654457868345852</iban>
            <depositor>
                <firstName>I'll</firstName>
                <middleName>Be</middleName>
                <lastName>Backovich</lastName>
                <identification>6548525F354DS2</identification>
            </depositor>
            <depositDate>2019-03-15</depositDate>
            <amount>600</amount>
            <currency>USD</currency>
            <profitability>24</profitability>
            <term>7</term>
            <withdrawal>true</withdrawal>
            <refill>true</refill>
            <capitalization>false</capitalization>
        </deposit>
    </bank>
    <bank country="Беларусь" site="www.belinvestbank.by" licence="true">
        <name>БелИнвестБанк</name>
        <deposit ID="DD0010">
            <type>Накопительный</type>
            <iban>BY34IDBN15478665431687649352</iban>
            <depositor>
                <firstName>Паблик</firstName>
                <middleName>Войд</middleName>
                <lastName>Мейнович</lastName>
                <identification>7634985F354DS2</identification>
            </depositor>
            <depositDate>2016-05-05</depositDate>
            <amount>550.40</amount>
            <currency>EUR</currency>
            <profitability>6.7</profitability>
            <term>24</term>
            <withdrawal>true</withdrawal>
            <refill>true</refill>
            <capitalization>false</capitalization>
        </deposit>
    </bank>
    <bank country="Беларусь" site="www.bnb.by" licence="false">
        <name>Белорусский Народный Банк</name>
        <deposit ID="DD0011" xsi:type="savingDeposit">
            <type>Сберегательный</type>
            <iban>BY34MMBN15477546873645861357</iban>
            <depositor>
                <firstName>Влево</firstName>
                <middleName>Вправо</middleName>
                <lastName>Неопределившевич</lastName>
                <identification>7685755C354SD2</identification>
            </depositor>
            <depositDate>2019-06-21</depositDate>
            <amount>470</amount>
            <currency>RUB</currency>
            <profitability>13.7</profitability>
            <term>36</term>
            <withdrawal>false</withdrawal>
            <refill>false</refill>
            <capitalization>false</capitalization>
            <payout>В конце срока</payout>
        </deposit>
    </bank>
    <bank country="Беларусь" site="www.rrb.by" licence="true">
        <name>РРБ-Банк</name>
        <deposit ID="DD0012">
            <type>До востребования</type>
            <iban>BY51MMBN86575672672567383465</iban>
